name: HSMaster

options:
  bundleIdPrefix: com.davideruisi
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 2
  xcodeVersion: "13.0"
  deploymentTarget: 
    iOS: "13.0"
  generateEmptyDirectories: true

targets:
  HSMaster:
    type: application
    platform: iOS
    sources:
      - HSMaster
    configFiles:
      Debug: HSMaster/SupportingFiles/Debug.xcconfig
      Release: HSMaster/SupportingFiles/Release.xcconfig
    info:
      path: HSMaster/SupportingFiles/Info.plist
      properties:
        # System
        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchStoryboardName: "LaunchScreen"
        UIRequiredDeviceCapabilities: ["armv7"]
        UISupportedInterfaceOrientations: ["UIInterfaceOrientationPortrait"]
        # HSMaster
        CONTENTFUL_SPACE_ID: $(CONTENTFUL_SPACE_ID)
        CONTENTFUL_ACCESS_TOKEN: $(CONTENTFUL_ACCESS_TOKEN)
        BATTLE_NET_CLIENT_ID: $(BATTLE_NET_CLIENT_ID)
        BATTLE_NET_CLIENT_SECRET: $(BATTLE_NET_CLIENT_SECRET)
        KEYCHAIN_SERVICE_ACCESS_TOKEN: $(KEYCHAIN_SERVICE_ACCESS_TOKEN)
        KEYCHAIN_ACCOUNT_BATTLE_NET: $(KEYCHAIN_ACCOUNT_BATTLE_NET)
    settings:
      TARGETED_DEVICE_FAMILY: 1
    preBuildScripts:
      - script: |
          if which "${PODS_ROOT}/SwiftLint/swiftlint" >/dev/null; then
            ${PODS_ROOT}/SwiftLint/swiftlint autocorrect && ${PODS_ROOT}/SwiftLint/swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: SwiftLint
      - script: |
          if [[ -f "${PODS_ROOT}/SwiftGen/bin/swiftgen" ]]; then
            "${PODS_ROOT}/SwiftGen/bin/swiftgen"
          else
            echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
          fi
        name: SwiftGen
